---
title: "Yield"
author: "Zhang Zhenglin"
output:
  pdf_document:
    toc: yes
editor_options:
  markdown:
    wrap: sentence
---

# Necessary libraries

```{r message=FALSE,warning=FALSE}
library(knitr)
library(ggplot2)
theme_set(theme_bw())
library(emmeans)
library(multcomp)
library(PLS205)
library(lme4)
library(lmerTest)
library(multcompView)
library(car)
library(Rmisc) 
library(dplyr) #https://r4ds.had.co.nz/ (Chapter 3, Chapter 5, look at filter and select)
# https://bookdown.org/ansellbr/WEHI_tidyR_course_book/
library(stringr) 
library(data.table)
library(GGally)
library(formatR)
library(readxl)
library(FluxCalR)
library(tidyverse)
library(fuzzyjoin)
library(purrr)
library(data.table)
library(broom)
library(lubridate)
library(readxl)
library(openxlsx)
library(ggrepel)
```

# Read data

```{r}
field <- read_excel("../Yield/Full_SubSample_2025.xlsx", sheet = 1)
str(field) #this is just the field datasheet lol

lab <- read_excel("../Yield/RES_field_datasheet_jdx.xlsx", sheet = 1)
str(lab) # this was after drying in lab, hand stripping and "official" yield quantification

combined <- field %>%
  full_join(lab, by = "Plot") %>%
  arrange(Plot)

combined$Plot <- as.factor(combined$Plot)

str(combined)
```

# Calculate yield


```{r}
combined$yield_Mg_ha <- ((combined$Total_sample_weight_g-combined$Tare_weight_g)/(combined$Sub_sample_weight_g-combined$Tare_weight_g)*(combined$OD_Gain_g))/100*(98.1/86)
#use (full/sub)*OD_dry_grain to get dry grain per plot (m2)
#scale g/m2 to Mg/ha, adjust moisture to 14%

yield <- combined %>% 
  select(Plot, yield_Mg_ha) %>%
  mutate(Treatment = factor(str_sub(Plot, 2)))

model <- lm(yield_Mg_ha~Treatment, data = yield)
anova(model)
means <- emmeans(model, spec = "Treatment")
cld(means)

ggplot(yield,
       aes(x=Treatment, y=yield_Mg_ha))+
  geom_boxplot()+
  geom_point()
```
